### ISSUE TITLE
コマンド終了後にウィンドウを残すオプションが欲しいです

### ISSUE THREAD

**Issue by cagechi** [rururutan/ckw-mod#2]
minttyの --hold (always)オプションみたいなものがあると
便利かなと思います。
ご検討よろしくお願いします。

**Comment by rururutan** [comment]
今一使用用途が分からないのですが、何に使うのでしょうか？

**Comment by cagechi** [comment]
シェルを起動するのではなく、スクリプトなどを単体起動した場合の
結果確認を行いたいためです。

**Comment by rururutan** [comment]
noAutoCloseオプションを追加しました。
